// Auto-generated by render-server.js — Whisper transcription
// Generated at: 2026-06-06T11:02:01.776Z

export type WordTiming  = { word: string; startFrame: number; endFrame: number };
export type CaptionChunk = { words: WordTiming[]; startFrame: number; endFrame: number };

export const TOTAL_FRAMES = 1785;

export const CAPTIONS: CaptionChunk[] = [
  { words: [
    { word: "Ich", startFrame: 0, endFrame: 13 },
    { word: "habe", startFrame: 13, endFrame: 20 },
    { word: "die", startFrame: 20, endFrame: 27 },
    { word: "chaotischste", startFrame: 27, endFrame: 52 }
  ], startFrame: 0, endFrame: 52 },
  { words: [
    { word: "Regency", startFrame: 52, endFrame: 67 },
    { word: "-Heldin", startFrame: 67, endFrame: 79 },
    { word: "geschrieben,", startFrame: 79, endFrame: 90 },
    { word: "die", startFrame: 95, endFrame: 95 }
  ], startFrame: 52, endFrame: 95 },
  { words: [
    { word: "ich", startFrame: 95, endFrame: 98 },
    { word: "mir", startFrame: 98, endFrame: 107 },
    { word: "vorstellen", startFrame: 107, endFrame: 122 },
    { word: "konnte.", startFrame: 122, endFrame: 136 }
  ], startFrame: 95, endFrame: 136 },
  { words: [
    { word: "Und", startFrame: 161, endFrame: 173 },
    { word: "irgendwie", startFrame: 173, endFrame: 186 },
    { word: "wurde", startFrame: 186, endFrame: 193 },
    { word: "sie", startFrame: 193, endFrame: 199 }
  ], startFrame: 161, endFrame: 199 },
  { words: [
    { word: "zu", startFrame: 199, endFrame: 205 },
    { word: "meiner", startFrame: 205, endFrame: 212 },
    { word: "Lieblingsfigur.", startFrame: 212, endFrame: 248 },
    { word: "Lady", startFrame: 271, endFrame: 279 }
  ], startFrame: 199, endFrame: 279 },
  { words: [
    { word: "Calamity", startFrame: 279, endFrame: 299 },
    { word: "zerstört", startFrame: 299, endFrame: 316 },
    { word: "Kronleuchter,", startFrame: 316, endFrame: 345 },
    { word: "ruiniert", startFrame: 353, endFrame: 368 }
  ], startFrame: 279, endFrame: 368 },
  { words: [
    { word: "Gesellschaftsabende", startFrame: 368, endFrame: 406 },
    { word: "und", startFrame: 406, endFrame: 419 },
    { word: "treibt", startFrame: 419, endFrame: 430 },
    { word: "einen", startFrame: 430, endFrame: 440 }
  ], startFrame: 368, endFrame: 440 },
  { words: [
    { word: "unglaublich", startFrame: 440, endFrame: 469 },
    { word: "abergläubischen", startFrame: 469, endFrame: 492 },
    { word: "Earl", startFrame: 492, endFrame: 502 },
    { word: "langsam", startFrame: 502, endFrame: 526 }
  ], startFrame: 440, endFrame: 526 },
  { words: [
    { word: "in", startFrame: 526, endFrame: 533 },
    { word: "den", startFrame: 533, endFrame: 538 },
    { word: "Wahnsinn.", startFrame: 538, endFrame: 557 },
    { word: "Jedes", startFrame: 598, endFrame: 612 }
  ], startFrame: 526, endFrame: 612 },
  { words: [
    { word: "Mal,", startFrame: 612, endFrame: 618 },
    { word: "wenn", startFrame: 618, endFrame: 622 },
    { word: "er", startFrame: 622, endFrame: 628 },
    { word: "versucht,", startFrame: 628, endFrame: 637 }
  ], startFrame: 612, endFrame: 637 },
  { words: [
    { word: "drei", startFrame: 644, endFrame: 647 },
    { word: "Schritte", startFrame: 647, endFrame: 658 },
    { word: "Abstand", startFrame: 658, endFrame: 670 },
    { word: "zu", startFrame: 670, endFrame: 678 }
  ], startFrame: 644, endFrame: 678 },
  { words: [
    { word: "halten,", startFrame: 678, endFrame: 688 },
    { word: "wird", startFrame: 700, endFrame: 703 },
    { word: "alles", startFrame: 703, endFrame: 714 },
    { word: "nur", startFrame: 714, endFrame: 722 }
  ], startFrame: 678, endFrame: 722 },
  { words: [
    { word: "noch", startFrame: 722, endFrame: 730 },
    { word: "schlimmer.", startFrame: 730, endFrame: 756 },
    { word: "Vor", startFrame: 760, endFrame: 769 },
    { word: "allem,", startFrame: 769, endFrame: 777 }
  ], startFrame: 722, endFrame: 777 },
  { words: [
    { word: "wenn", startFrame: 778, endFrame: 782 },
    { word: "eine", startFrame: 782, endFrame: 792 },
    { word: "Ziege", startFrame: 792, endFrame: 804 },
    { word: "namens", startFrame: 804, endFrame: 814 }
  ], startFrame: 778, endFrame: 814 },
  { words: [
    { word: "Periwinkle", startFrame: 814, endFrame: 836 },
    { word: "beschließt,", startFrame: 836, endFrame: 853 },
    { word: "mitzuhelfen.", startFrame: 856, endFrame: 880 },
    { word: "Doch", startFrame: 902, endFrame: 914 }
  ], startFrame: 814, endFrame: 914 },
  { words: [
    { word: "unter", startFrame: 914, endFrame: 925 },
    { word: "all", startFrame: 925, endFrame: 932 },
    { word: "dem", startFrame: 932, endFrame: 937 },
    { word: "Chaos", startFrame: 937, endFrame: 952 }
  ], startFrame: 914, endFrame: 952 },
  { words: [
    { word: "steckt", startFrame: 952, endFrame: 970 },
    { word: "eine", startFrame: 970, endFrame: 978 },
    { word: "liebevolle", startFrame: 978, endFrame: 1000 },
    { word: "Slowburn", startFrame: 1000, endFrame: 1018 }
  ], startFrame: 952, endFrame: 1018 },
  { words: [
    { word: "-Romanze", startFrame: 1018, endFrame: 1045 },
    { word: "über", startFrame: 1045, endFrame: 1057 },
    { word: "zwei", startFrame: 1057, endFrame: 1069 },
    { word: "Menschen,", startFrame: 1069, endFrame: 1082 }
  ], startFrame: 1018, endFrame: 1082 },
  { words: [
    { word: "die", startFrame: 1091, endFrame: 1091 },
    { word: "erkennen,", startFrame: 1091, endFrame: 1102 },
    { word: "dass", startFrame: 1116, endFrame: 1119 },
    { word: "gerade", startFrame: 1119, endFrame: 1132 }
  ], startFrame: 1091, endFrame: 1132 },
  { words: [
    { word: "unsere", startFrame: 1132, endFrame: 1141 },
    { word: "Fehler", startFrame: 1141, endFrame: 1153 },
    { word: "uns", startFrame: 1153, endFrame: 1163 },
    { word: "liebenswert", startFrame: 1163, endFrame: 1178 }
  ], startFrame: 1132, endFrame: 1178 },
  { words: [
    { word: "machen.", startFrame: 1178, endFrame: 1191 },
    { word: "Beim", startFrame: 1229, endFrame: 1235 },
    { word: "Schreiben", startFrame: 1235, endFrame: 1247 },
    { word: "dieser", startFrame: 1247, endFrame: 1256 }
  ], startFrame: 1178, endFrame: 1256 },
  { words: [
    { word: "Geschichte", startFrame: 1256, endFrame: 1268 },
    { word: "musste", startFrame: 1268, endFrame: 1277 },
    { word: "ich", startFrame: 1277, endFrame: 1285 },
    { word: "ständig", startFrame: 1285, endFrame: 1298 }
  ], startFrame: 1256, endFrame: 1298 },
  { words: [
    { word: "lachen", startFrame: 1298, endFrame: 1312 },
    { word: "und", startFrame: 1312, endFrame: 1324 },
    { word: "noch", startFrame: 1324, endFrame: 1333 },
    { word: "heute", startFrame: 1333, endFrame: 1342 }
  ], startFrame: 1298, endFrame: 1342 },
  { words: [
    { word: "zaubert", startFrame: 1342, endFrame: 1353 },
    { word: "sie", startFrame: 1353, endFrame: 1358 },
    { word: "mir", startFrame: 1358, endFrame: 1363 },
    { word: "ein", startFrame: 1363, endFrame: 1367 }
  ], startFrame: 1342, endFrame: 1367 },
  { words: [
    { word: "Lächeln", startFrame: 1367, endFrame: 1376 },
    { word: "ins", startFrame: 1376, endFrame: 1383 },
    { word: "Gesicht.", startFrame: 1383, endFrame: 1397 },
    { word: "Wenn", startFrame: 1423, endFrame: 1428 }
  ], startFrame: 1367, endFrame: 1428 },
  { words: [
    { word: "du", startFrame: 1428, endFrame: 1433 },
    { word: "Regency", startFrame: 1433, endFrame: 1451 },
    { word: "-Romane", startFrame: 1451, endFrame: 1466 },
    { word: "mit", startFrame: 1466, endFrame: 1474 }
  ], startFrame: 1428, endFrame: 1474 },
  { words: [
    { word: "Humor,", startFrame: 1474, endFrame: 1494 },
    { word: "Herz", startFrame: 1507, endFrame: 1513 },
    { word: "und", startFrame: 1513, endFrame: 1526 },
    { word: "einer", startFrame: 1526, endFrame: 1533 }
  ], startFrame: 1474, endFrame: 1533 },
  { words: [
    { word: "gehörigen", startFrame: 1533, endFrame: 1550 },
    { word: "Portion", startFrame: 1550, endFrame: 1566 },
    { word: "Chaos", startFrame: 1566, endFrame: 1579 },
    { word: "liebst,", startFrame: 1579, endFrame: 1594 }
  ], startFrame: 1533, endFrame: 1594 },
  { words: [
    { word: "dann", startFrame: 1606, endFrame: 1610 },
    { word: "wirf", startFrame: 1610, endFrame: 1619 },
    { word: "einen", startFrame: 1619, endFrame: 1625 },
    { word: "Blick", startFrame: 1625, endFrame: 1632 }
  ], startFrame: 1606, endFrame: 1632 },
  { words: [
    { word: "auf", startFrame: 1632, endFrame: 1640 },
    { word: "Lady", startFrame: 1640, endFrame: 1651 },
    { word: "Calamities", startFrame: 1651, endFrame: 1669 },
    { word: "Glücksbringer.", startFrame: 1669, endFrame: 1690 }
  ], startFrame: 1632, endFrame: 1690 },
  { words: [
    { word: "Ich", startFrame: 1690, endFrame: 1719 },
    { word: "hoffe,", startFrame: 1719, endFrame: 1727 },
    { word: "du", startFrame: 1729, endFrame: 1735 },
    { word: "verliebst", startFrame: 1735, endFrame: 1745 }
  ], startFrame: 1690, endFrame: 1745 },
  { words: [
    { word: "dich", startFrame: 1745, endFrame: 1753 },
    { word: "genauso", startFrame: 1753, endFrame: 1765 },
    { word: "in", startFrame: 1765, endFrame: 1774 },
    { word: "diese", startFrame: 1774, endFrame: 1777 }
  ], startFrame: 1745, endFrame: 1777 },
  { words: [
    { word: "Geschichte.", startFrame: 1777, endFrame: 1785 }
  ], startFrame: 1777, endFrame: 1785 }
];
