// Auto-generated by render-server.js — Whisper transcription
// Generated at: 2026-05-27T18:07:06.190Z

export type WordTiming = {
  word: string;
  startFrame: number;
  endFrame: number;
};

export type CaptionChunk = {
  words: WordTiming[];
  startFrame: number;
  endFrame: number;
};

export const TOTAL_FRAMES = 1352;

export const CAPTIONS: CaptionChunk[] = [
  { words: [
    { word: "I", startFrame: 0, endFrame: 19 },
    { word: "just", startFrame: 19, endFrame: 31 },
    { word: "finished", startFrame: 31, endFrame: 47 },
    { word: "the", startFrame: 47, endFrame: 65 }
  ], startFrame: 0, endFrame: 65 },
  { words: [
    { word: "sweetest", startFrame: 65, endFrame: 98 },
    { word: "Regency", startFrame: 98, endFrame: 112 },
    { word: "romance.", startFrame: 112, endFrame: 130 },
    { word: "The", startFrame: 146, endFrame: 155 }
  ], startFrame: 65, endFrame: 155 },
  { words: [
    { word: "wallflower", startFrame: 155, endFrame: 171 },
    { word: "who", startFrame: 171, endFrame: 181 },
    { word: "knew", startFrame: 181, endFrame: 190 },
    { word: "everything", startFrame: 190, endFrame: 208 }
  ], startFrame: 155, endFrame: 208 },
  { words: [
    { word: "by", startFrame: 208, endFrame: 217 },
    { word: "Margaret", startFrame: 217, endFrame: 230 },
    { word: "Ellington", startFrame: 230, endFrame: 251 },
    { word: "completely", startFrame: 251, endFrame: 277 }
  ], startFrame: 208, endFrame: 277 },
  { words: [
    { word: "stole", startFrame: 277, endFrame: 288 },
    { word: "my", startFrame: 288, endFrame: 297 },
    { word: "heart.", startFrame: 297, endFrame: 313 },
    { word: "Quiet", startFrame: 333, endFrame: 340 }
  ], startFrame: 277, endFrame: 340 },
  { words: [
    { word: "Rose", startFrame: 340, endFrame: 350 },
    { word: "has", startFrame: 350, endFrame: 359 },
    { word: "spent", startFrame: 359, endFrame: 368 },
    { word: "years", startFrame: 368, endFrame: 386 }
  ], startFrame: 340, endFrame: 386 },
  { words: [
    { word: "hiding", startFrame: 386, endFrame: 396 },
    { word: "in", startFrame: 396, endFrame: 402 },
    { word: "the", startFrame: 402, endFrame: 407 },
    { word: "shadows,", startFrame: 407, endFrame: 421 }
  ], startFrame: 386, endFrame: 421 },
  { words: [
    { word: "knowing", startFrame: 432, endFrame: 442 },
    { word: "everyone's", startFrame: 442, endFrame: 470 },
    { word: "secrets", startFrame: 470, endFrame: 482 },
    { word: "but", startFrame: 482, endFrame: 495 }
  ], startFrame: 432, endFrame: 495 },
  { words: [
    { word: "never", startFrame: 495, endFrame: 508 },
    { word: "using", startFrame: 508, endFrame: 520 },
    { word: "them.", startFrame: 520, endFrame: 536 },
    { word: "Until", startFrame: 546, endFrame: 563 }
  ], startFrame: 495, endFrame: 563 },
  { words: [
    { word: "the", startFrame: 563, endFrame: 572 },
    { word: "handsome", startFrame: 572, endFrame: 588 },
    { word: "new", startFrame: 588, endFrame: 597 },
    { word: "Duke", startFrame: 597, endFrame: 603 }
  ], startFrame: 563, endFrame: 603 },
  { words: [
    { word: "of", startFrame: 603, endFrame: 611 },
    { word: "Carlisle", startFrame: 611, endFrame: 624 },
    { word: "is", startFrame: 624, endFrame: 630 },
    { word: "being", startFrame: 630, endFrame: 640 }
  ], startFrame: 603, endFrame: 640 },
  { words: [
    { word: "blackmailed", startFrame: 640, endFrame: 673 },
    { word: "and", startFrame: 673, endFrame: 680 },
    { word: "she", startFrame: 680, endFrame: 691 },
    { word: "boldly", startFrame: 691, endFrame: 709 }
  ], startFrame: 640, endFrame: 709 },
  { words: [
    { word: "steps", startFrame: 709, endFrame: 716 },
    { word: "in", startFrame: 716, endFrame: 724 },
    { word: "to", startFrame: 724, endFrame: 728 },
    { word: "help", startFrame: 728, endFrame: 734 }
  ], startFrame: 709, endFrame: 734 },
  { words: [
    { word: "him.", startFrame: 734, endFrame: 747 },
    { word: "What", startFrame: 747, endFrame: 767 },
    { word: "starts", startFrame: 767, endFrame: 781 },
    { word: "as", startFrame: 781, endFrame: 793 }
  ], startFrame: 734, endFrame: 793 },
  { words: [
    { word: "a", startFrame: 793, endFrame: 797 },
    { word: "secret", startFrame: 797, endFrame: 805 },
    { word: "arrangement", startFrame: 805, endFrame: 824 },
    { word: "turns", startFrame: 824, endFrame: 839 }
  ], startFrame: 793, endFrame: 839 },
  { words: [
    { word: "into", startFrame: 839, endFrame: 851 },
    { word: "something", startFrame: 851, endFrame: 865 },
    { word: "so", startFrame: 865, endFrame: 884 },
    { word: "much", startFrame: 884, endFrame: 892 }
  ], startFrame: 839, endFrame: 892 },
  { words: [
    { word: "more.", startFrame: 892, endFrame: 904 },
    { word: "It's", startFrame: 922, endFrame: 933 },
    { word: "warm,", startFrame: 933, endFrame: 948 },
    { word: "tender,", startFrame: 961, endFrame: 973 }
  ], startFrame: 892, endFrame: 973 },
  { words: [
    { word: "funny,", startFrame: 986, endFrame: 992 },
    { word: "and", startFrame: 1010, endFrame: 1013 },
    { word: "gave", startFrame: 1013, endFrame: 1019 },
    { word: "me", startFrame: 1019, endFrame: 1031 }
  ], startFrame: 986, endFrame: 1031 },
  { words: [
    { word: "all", startFrame: 1031, endFrame: 1042 },
    { word: "the", startFrame: 1042, endFrame: 1047 },
    { word: "butterflies", startFrame: 1047, endFrame: 1062 },
    { word: "watching", startFrame: 1062, endFrame: 1075 }
  ], startFrame: 1031, endFrame: 1075 },
  { words: [
    { word: "her", startFrame: 1075, endFrame: 1085 },
    { word: "finally", startFrame: 1085, endFrame: 1101 },
    { word: "step", startFrame: 1101, endFrame: 1111 },
    { word: "into", startFrame: 1111, endFrame: 1119 }
  ], startFrame: 1075, endFrame: 1119 },
  { words: [
    { word: "the", startFrame: 1119, endFrame: 1124 },
    { word: "light.", startFrame: 1124, endFrame: 1132 },
    { word: "If", startFrame: 1153, endFrame: 1158 },
    { word: "you", startFrame: 1158, endFrame: 1166 }
  ], startFrame: 1119, endFrame: 1166 },
  { words: [
    { word: "love", startFrame: 1166, endFrame: 1175 },
    { word: "clean,", startFrame: 1175, endFrame: 1190 },
    { word: "emotional", startFrame: 1201, endFrame: 1219 },
    { word: "Regency", startFrame: 1219, endFrame: 1235 }
  ], startFrame: 1166, endFrame: 1235 },
  { words: [
    { word: "romances", startFrame: 1235, endFrame: 1253 },
    { word: "with", startFrame: 1253, endFrame: 1261 },
    { word: "heart,", startFrame: 1261, endFrame: 1270 },
    { word: "this", startFrame: 1286, endFrame: 1294 }
  ], startFrame: 1235, endFrame: 1294 },
  { words: [
    { word: "one", startFrame: 1294, endFrame: 1303 },
    { word: "is", startFrame: 1303, endFrame: 1319 },
    { word: "pure", startFrame: 1319, endFrame: 1334 },
    { word: "magic.", startFrame: 1334, endFrame: 1352 }
  ], startFrame: 1294, endFrame: 1352 }
];
