import React from "react";
import {
  AbsoluteFill,
  Audio,
  Video,
  Img,
  Series,
  interpolate,
  useCurrentFrame,
  staticFile,
} from "remotion";
import type { WordTiming, CaptionChunk } from "./captions-data";
import { CAPTIONS, TOTAL_FRAMES } from "./captions-data";

// ═══════════════════════════════════════════════════════════════════
// CAPTIONS (WHISPER-READY ARCHITECTURE)
// Data from ./captions-data.ts — regenerated by render-server on each render
// ═══════════════════════════════════════════════════════════════════
const CAPTION_STYLE = {
  fontFamily: "'Arial Black', 'Helvetica Neue', sans-serif",
  fontSize: 82,
  activeColor: "#FFE600",
  inactiveColor: "#FFFFFF",
  strokeColor: "#000000",
  strokeWidth: 14,
  bgColor: "rgba(0,0,0,0.0)",
  positionY: "72%",
  lineHeight: 1.15,
  letterSpacing: 1,
  maxWidth: 900,
};

// ═══════════════════════════════════════════════════════════════════
// TIMELINE
// ═══════════════════════════════════════════════════════════════════
type VideoClipData = {
  type: "video";
  source: string;
  scale: number;
  yOffset?: number;
  startFrame: number;
  endFrame: number;
  isMasterSync?: boolean;
};

type ImageClipData = {
  type: "image";
  source: string;
  startFrame: number;
  endFrame: number;
  startScale: number;
  endScale: number;
  driftX: number;
  driftY: number;
  // NEW: focal point for objectPosition — creates the illusion of different shots
  objectPosition?: string;
  // NEW: subtle color overlay to shift the mood per clip
  colorOverlay?: string;
  // NEW: long-form fade for special end card
  fadeInFrames?: number;
  fadeOutFrames?: number;
};

type ClipData = VideoClipData | ImageClipData;

const TIMELINE_DATA: ClipData[] = [
  // ── 0–65: Hook (Speaker) ───────────────────────────────────────
  {
    type: "video",
    source: "fourdances.mp4",
    startFrame: 0,
    endFrame: 65,
    scale: 1.0,
    isMasterSync: true,
  },

  // ── 66–157: TITLE DROP — 1.png Effect A ───────────────────────
  // Focal point: Kindle screen (center-ish, slightly low)
  // Direction: slow push-IN, drift top-right → warm amber tint
  {
    type: "image",
    source: "1.png",
    startFrame: 66,
    endFrame: 157,
    startScale: 1.0,
    endScale: 1.12,
    driftX: 6,
    driftY: -7,
    objectPosition: "40% 58%",
    colorOverlay: "rgba(255, 200, 100, 0.07)",
  },

  // ── 158–360: Speaker ("Four Dances…smiling and kicking my feet") 
  {
    type: "video",
    source: "fourdances.mp4",
    startFrame: 158,
    endFrame: 360,
    scale: 1.0,
    isMasterSync: true,
  },

  // ── 361–518: 1.png Effect B ────────────────────────────────────
  // Focal point: candle / flowers area (upper-left corner)
  // Direction: starts ZOOMED IN, slowly pulls back — opposite movement
  // Tint: faint lilac (twilight feel, atmospheric contrast)
  {
    type: "image",
    source: "1.png",
    startFrame: 361,
    endFrame: 518,
    startScale: 1.18,
    endScale: 1.06,
    driftX: -7,
    driftY: 5,
    objectPosition: "18% 20%",
    colorOverlay: "rgba(210, 190, 255, 0.06)",
  },

  // ── 519–650: Speaker (Viscount Pembridge / crazy bet) ──────────
  {
    type: "video",
    source: "fourdances.mp4",
    startFrame: 519,
    endFrame: 650,
    scale: 1.02,
    yOffset: -5,
    isMasterSync: true,
  },

  // ── 651–760: 1.png Effect C ────────────────────────────────────
  // Focal point: hand + blanket (bottom-left warmth)
  // Direction: slow push-IN + drift upward — cosy garden shed mood
  // Tint: warm golden-orange
  {
    type: "image",
    source: "1.png",
    startFrame: 651,
    endFrame: 760,
    startScale: 1.07,
    endScale: 1.17,
    driftX: 3,
    driftY: -9,
    objectPosition: "24% 82%",
    colorOverlay: "rgba(255, 170, 70, 0.09)",
  },

  // ── 761–830: Speaker ("What happens? Secret dance lessons…") ───
  {
    type: "video",
    source: "fourdances.mp4",
    startFrame: 761,
    endFrame: 830,
    scale: 1.0,
    isMasterSync: true,
  },

  // ── 831–960: 1.png Effect D ────────────────────────────────────
  // Focal point: flowers / top of scene only
  // Direction: dramatic push-IN, slow drift down — reveals warmth below
  // Tint: soft honey gold — "butterflies" visual metaphor
  {
    type: "image",
    source: "1.png",
    startFrame: 831,
    endFrame: 960,
    startScale: 1.10,
    endScale: 1.22,
    driftX: -4,
    driftY: 7,
    objectPosition: "52% 10%",
    colorOverlay: "rgba(255, 235, 150, 0.07)",
  },

  // ── 961–1058: Speaker ("It's sweet, funny, clean…butterflies") ─
  {
    type: "video",
    source: "fourdances.mp4",
    startFrame: 961,
    endFrame: 1058,
    scale: 1.0,
    isMasterSync: true,
  },

  // ── 1059–1217: end.png — CTA FINALE ───────────────────────────
  // Slow cinematic push-in from wide
  // Long 20-frame fade-in for a dramatic "reveal" feel
  // Rich golden warmth — the emotional landing of the whole reel
  {
    type: "image",
    source: "end.png",
    startFrame: 1059,
    endFrame: TOTAL_FRAMES,
    startScale: 1.02,
    endScale: 1.11,
    driftX: 0,
    driftY: -6,
    objectPosition: "center center",
    colorOverlay: "rgba(255, 215, 110, 0.10)",
    fadeInFrames: 20,
    fadeOutFrames: 3,
  },
];

// ─── CONSTANTS ──────────────────────────────────────────────────
const FADE_FRAMES  = 5;
const FLASH_FRAMES = 1;

// ─── EFFECTS ────────────────────────────────────────────────────
const Vignette: React.FC = () => (
  <AbsoluteFill
    style={{
      background:
        "radial-gradient(ellipse at 50% 50%, transparent 52%, rgba(0,0,0,0.72) 100%)",
      pointerEvents: "none",
      zIndex: 10,
    }}
  />
);

const FilmGrain: React.FC = () => {
  const frame = useCurrentFrame();
  const seed  = (frame * 97) % 200;
  return (
    <AbsoluteFill
      style={{ pointerEvents: "none", zIndex: 11, opacity: 0.04, overflow: "hidden" }}
    >
      <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
        <filter id="grain">
          <feTurbulence
            type="fractalNoise"
            baseFrequency="0.72"
            numOctaves="4"
            seed={seed}
            stitchTiles="stitch"
          />
          <feColorMatrix type="saturate" values="0" />
        </filter>
        <rect width="100%" height="100%" filter="url(#grain)" />
      </svg>
    </AbsoluteFill>
  );
};

const CutFlash: React.FC = () => {
  const frame = useCurrentFrame();
  const flashOpacity = interpolate(
    frame,
    [0, FLASH_FRAMES, FLASH_FRAMES + 1],
    [0.15, 0.15, 0],
    { extrapolateRight: "clamp" }
  );
  return (
    <AbsoluteFill
      style={{
        backgroundColor: `rgba(255,255,255,${flashOpacity})`,
        pointerEvents: "none",
        zIndex: 12,
      }}
    />
  );
};

// ─── CAPTIONS LAYER ─────────────────────────────────────────────
// Captions always render — no more quote-frame suppression
const CaptionsLayer: React.FC = () => {
  const frame = useCurrentFrame();
  const s     = CAPTION_STYLE;

  const chunk = CAPTIONS.find((c) => frame >= c.startFrame && frame <= c.endFrame);
  if (!chunk) return null;

  const chunkDuration = chunk.endFrame - chunk.startFrame;
  const frameInChunk  = frame - chunk.startFrame;
  const activeWordIdx = chunk.words.findIndex(
    (w) => frame >= w.startFrame && frame < w.endFrame
  );

  const chunkEntrance = interpolate(frameInChunk, [0, 6], [18, 0], { extrapolateRight: "clamp" });
  const chunkOpacity  = interpolate(frameInChunk, [0, 5], [0, 1], { extrapolateRight: "clamp" });
  const exitOpacity   = interpolate(
    frameInChunk,
    [chunkDuration - 4, chunkDuration],
    [1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" }
  );
  const finalOpacity = Math.min(chunkOpacity, exitOpacity);

  return (
    <AbsoluteFill
      style={{
        zIndex: 20,
        pointerEvents: "none",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        position: "absolute",
        top: s.positionY,
        left: 0,
        width: "100%",
        paddingLeft: (1080 - s.maxWidth) / 2,
        paddingRight: (1080 - s.maxWidth) / 2,
      }}
    >
      <div
        style={{
          display: "flex",
          flexWrap: "wrap",
          justifyContent: "center",
          alignItems: "center",
          gap: "0 16px",
          opacity: finalOpacity,
          transform: `translateY(${chunkEntrance}px)`,
          background: s.bgColor,
          borderRadius: 16,
          padding: s.bgColor !== "rgba(0,0,0,0.0)" ? "8px 24px" : 0,
        }}
      >
        {chunk.words.map((timing, i) => {
          const isActive =
            i === activeWordIdx ||
            (activeWordIdx === -1 &&
              i === chunk.words.length - 1 &&
              frame >= timing.startFrame);

          const framesSinceActive = frame - timing.startFrame;
          const wordScale = interpolate(
            framesSinceActive,
            [0, 3, 6],
            [isActive ? 0.88 : 1.0, isActive ? 1.12 : 1.0, 1.0],
            { extrapolateLeft: "clamp", extrapolateRight: "clamp" }
          );

          return (
            <span
              key={i}
              style={{
                fontFamily: s.fontFamily,
                fontSize: s.fontSize,
                fontWeight: 900,
                lineHeight: s.lineHeight,
                letterSpacing: s.letterSpacing,
                textTransform: "uppercase",
                color: isActive ? s.activeColor : s.inactiveColor,
                textShadow: [
                  `${s.strokeWidth / 2}px 0 0 ${s.strokeColor}`,
                  `-${s.strokeWidth / 2}px 0 0 ${s.strokeColor}`,
                  `0 ${s.strokeWidth / 2}px 0 ${s.strokeColor}`,
                  `0 -${s.strokeWidth / 2}px 0 ${s.strokeColor}`,
                  `${s.strokeWidth / 3}px ${s.strokeWidth / 3}px 0 ${s.strokeColor}`,
                  `-${s.strokeWidth / 3}px ${s.strokeWidth / 3}px 0 ${s.strokeColor}`,
                  `${s.strokeWidth / 3}px -${s.strokeWidth / 3}px 0 ${s.strokeColor}`,
                  `-${s.strokeWidth / 3}px -${s.strokeWidth / 3}px 0 ${s.strokeColor}`,
                  isActive ? `0 0 40px rgba(255,230,0,0.6)` : "",
                ]
                  .filter(Boolean)
                  .join(", "),
                display: "inline-block",
                transform: `scale(${wordScale})`,
                transformOrigin: "center bottom",
                transition: "color 0.04s",
                whiteSpace: "nowrap",
              }}
            >
              {timing.word}
            </span>
          );
        })}
      </div>
    </AbsoluteFill>
  );
};

// ─── VIDEO CLIP ─────────────────────────────────────────────────
const VideoClipEl: React.FC<{ clip: VideoClipData; duration: number }> = ({
  clip,
  duration,
}) => {
  const frame = useCurrentFrame();

  const opacity = interpolate(
    frame,
    [0, FADE_FRAMES, duration - FADE_FRAMES, duration],
    [0, 1, 1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" }
  );

  const pushScale = interpolate(frame, [0, duration], [clip.scale, clip.scale + 0.01], {
    extrapolateRight: "clamp",
  });

  const transform = [
    `scale(${pushScale})`,
    `translateY(${clip.yOffset || 0}px)`,
  ].join(" ");

  const startFrom = clip.isMasterSync ? clip.startFrame : 0;
  const endAt     = clip.isMasterSync ? clip.startFrame + duration : duration;

  return (
    <AbsoluteFill style={{ opacity, backgroundColor: "#000" }}>
      <Video
        src={staticFile(clip.source)}
        startFrom={startFrom}
        endAt={endAt}
        muted
        style={{
          width: "100%",
          height: "100%",
          objectFit: "cover",
          transform,
        }}
      />
      <Vignette />
      <FilmGrain />
      <CutFlash />
    </AbsoluteFill>
  );
};

// ─── IMAGE CLIP ─────────────────────────────────────────────────
const ImageClipEl: React.FC<{ clip: ImageClipData; duration: number }> = ({
  clip,
  duration,
}) => {
  const frame = useCurrentFrame();

  // Customisable fade lengths (default to FADE_FRAMES)
  const fadeIn  = clip.fadeInFrames  ?? FADE_FRAMES;
  const fadeOut = clip.fadeOutFrames ?? FADE_FRAMES;

  const opacity = interpolate(
    frame,
    [0, fadeIn, duration - fadeOut, duration],
    [0, 1, 1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" }
  );

  // Ken Burns: main continuous movement
  const scale  = interpolate(frame, [0, duration], [clip.startScale, clip.endScale], {
    extrapolateRight: "clamp",
  });
  const driftX = interpolate(frame, [0, duration], [0, clip.driftX], {
    extrapolateRight: "clamp",
  });
  const driftY = interpolate(frame, [0, duration], [0, clip.driftY], {
    extrapolateRight: "clamp",
  });

  // Entry zoom pulse: a quick micro-bounce on the cut (0.97 → 1.04 → 1.00)
  // This gives every image-to-anything cut a punchy, energetic feel
  const entryPulse = interpolate(
    frame,
    [0, 6, 16],
    [0.97, 1.04, 1.0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" }
  );

  // Colour overlay fades in over 20 frames and out over last 8
  const overlayOpacity = clip.colorOverlay
    ? interpolate(frame, [0, 20, duration - 8, duration], [0, 1, 1, 0], {
        extrapolateLeft: "clamp",
        extrapolateRight: "clamp",
      })
    : 0;

  return (
    <AbsoluteFill style={{ opacity, backgroundColor: "#000", overflow: "hidden" }}>
      <Img
        src={staticFile(clip.source)}
        style={{
          width: "100%",
          height: "100%",
          objectFit: "cover",
          objectPosition: clip.objectPosition ?? "center center",
          transform: `scale(${scale * entryPulse}) translate(${driftX}px, ${driftY}px)`,
          transformOrigin: "center center",
        }}
      />

      {/* Mood colour overlay */}
      {clip.colorOverlay && (
        <AbsoluteFill
          style={{
            backgroundColor: clip.colorOverlay,
            opacity: overlayOpacity,
            pointerEvents: "none",
            zIndex: 5,
            mixBlendMode: "screen",
          }}
        />
      )}

      <Vignette />
      <FilmGrain />
      <CutFlash />
    </AbsoluteFill>
  );
};

// ─── ROOT COMPOSITION ───────────────────────────────────────────
export const BookTokTemplate: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: "#000" }}>
      {/* Master Audio Track */}
      <Audio src={staticFile("fourdances.mp4")} volume={1.0} />

      {/* Video / Image layer */}
      <Series>
        {TIMELINE_DATA.map((clip, index) => {
          const duration = clip.endFrame - clip.startFrame + 1;
          return (
            <Series.Sequence key={index} durationInFrames={duration}>
              {clip.type === "video" ? (
                <VideoClipEl clip={clip} duration={duration} />
              ) : (
                <ImageClipEl clip={clip as ImageClipData} duration={duration} />
              )}
            </Series.Sequence>
          );
        })}
      </Series>

      <CaptionsLayer />
    </AbsoluteFill>
  );
};